import { Platform, StyleSheet } from "react-native";

import { colors, radius, spacing } from "../../theme/tokens";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "rgba(6, 5, 4, 0.8)",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(6, 5, 4, 0.8)",
    padding: spacing.md,
  },
  panel: {
    flex: 1,
    backgroundColor: colors.panel,
    borderColor: colors.borderStrong,
    borderRadius: radius.xl,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.lg,
  },
  header: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  headerCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  eyebrow: {
    color: colors.goldSoft,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  title: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 28,
  },
  body: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  closeButton: {
    alignItems: "center",
    borderColor: colors.borderStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: spacing.md,
  },
  closeButtonText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  section: {
    gap: spacing.sm,
  },
  fallbackStack: {
    gap: spacing.sm,
  },
  fallbackCard: {
    backgroundColor: "rgba(128, 48, 27, 0.24)",
    borderColor: "rgba(224, 143, 98, 0.42)",
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.md,
  },
  fallbackTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  fallbackBody: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  sectionLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  cameraFrame: {
    backgroundColor: colors.canvas,
    borderRadius: radius.lg,
    flex: 1,
    minHeight: Platform.select({ ios: 320, default: 280 }),
    overflow: "hidden",
  },
  cameraFallback: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
  },
  cameraFallbackTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  cameraFallbackBody: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 22,
    marginTop: spacing.sm,
    textAlign: "center",
  },
  locationCard: {
    backgroundColor: colors.canvas,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.md,
  },
  locationValue: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 22,
  },
  locationMeta: {
    color: colors.textSoft,
    fontSize: 13,
    lineHeight: 20,
  },
  sectionActions: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  secondaryAction: {
    alignItems: "center",
    borderColor: colors.borderStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
  },
  secondaryActionPressed: {
    transform: [{ scale: 0.985 }],
  },
  secondaryActionDisabled: {
    opacity: 0.45,
  },
  secondaryActionText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  primaryActionShell: {
    backgroundColor: colors.gold,
    borderRadius: radius.pill,
    marginTop: "auto",
    padding: 4,
  },
  primaryActionPressed: {
    transform: [{ scale: 0.985 }],
  },
  primaryActionDisabled: {
    opacity: 0.65,
  },
  primaryActionCore: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  primaryActionText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  actionIsland: {
    alignItems: "center",
    backgroundColor: "rgba(15, 13, 11, 0.10)",
    borderRadius: radius.pill,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  actionIslandText: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "800",
    marginTop: -1,
  },
  errorText: {
    color: colors.danger,
    fontSize: 13,
    lineHeight: 20,
  },
});
